# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_tile_id', models.CharField(max_length=500)),
                ('app_page_id', models.CharField(max_length=500)),
                ('app_x_width', models.IntegerField(default=1)),
                ('app_y_width', models.IntegerField(default=1)),
                ('app_x_weight', models.IntegerField(default=1)),
                ('app_y_weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='installedapp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.User'),
        ),
    ]
