# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedapp',
            name='app_id',
            field=models.IntegerField(default=-1),
        ),
    ]
