# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_installedapp_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maxapp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='installedapp',
            name='app_id',
            field=models.IntegerField(auto_created=True),
        ),
    ]
